default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: challenge_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: challenge_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DATABASE_POOL"] || ENV['MAX_THREADS'] || 5 %>